<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>https://aibot88-wewe-rss.hf.space/feeds/all.atom</id>
    <title>WeWe-RSS All</title>
    <updated>2024-10-30T15:29:37.000Z</updated>
    <generator>WeWe-RSS</generator>
    <author>
        <name>WeWe-RSS All</name>
    </author>
    <link rel="alternate" href="https://aibot88-wewe-rss.hf.space/feeds/all.atom"/>
    <subtitle>WeWe-RSS 全部文章</subtitle>
    <logo>https://aibot88-wewe-rss.hf.space/favicon.ico</logo>
    <icon>https://aibot88-wewe-rss.hf.space/favicon.ico</icon>
    <entry>
        <title type="html"><![CDATA[2025年毕业生简历，我腆着老脸问了一圈没人要。为什么？]]></title>
        <id>YCdkVCfn28yy0lHAlT4fRA</id>
        <link href="https://mp.weixin.qq.com/s/YCdkVCfn28yy0lHAlT4fRA"/>
        <updated>2024-10-30T13:01:05.000Z</updated>
        <author>
            <name>BurpSuite实战教程</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[比kali更稳定，工具更多，更加适合开发的操作系统-Blackarch]]></title>
        <id>xAxa27musSiK4b3yiFvcig</id>
        <link href="https://mp.weixin.qq.com/s/xAxa27musSiK4b3yiFvcig"/>
        <updated>2024-10-30T04:41:31.000Z</updated>
        <author>
            <name>泷羽Sec</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[CVE-2024-42640 CVSS评分10.0 - Angular 未经身份验证的远程代码执行 附EXP]]></title>
        <id>v1HQnSCvcXO2uHDjeHqSGQ</id>
        <link href="https://mp.weixin.qq.com/s/v1HQnSCvcXO2uHDjeHqSGQ"/>
        <updated>2024-10-30T04:24:36.000Z</updated>
        <author>
            <name>合规渗透</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[Windows 主题文件0day有第三方补丁，官方还未修复]]></title>
        <id>DmK6xaJu_7ETwBNsL1guVA</id>
        <link href="https://mp.weixin.qq.com/s/DmK6xaJu_7ETwBNsL1guVA"/>
        <updated>2024-10-30T03:34:08.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[黑客用来窃取用户密码的顶级恶意软件]]></title>
        <id>xrJw71NUTxriVSOksNMCKw</id>
        <link href="https://mp.weixin.qq.com/s/xrJw71NUTxriVSOksNMCKw"/>
        <updated>2024-10-30T03:34:08.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[ATM漏洞在TikTok传播后给摩根大通带来数百万损失]]></title>
        <id>kq4kL6rIWL8nfl5Nh9igxA</id>
        <link href="https://mp.weixin.qq.com/s/kq4kL6rIWL8nfl5Nh9igxA"/>
        <updated>2024-10-30T03:34:08.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[IDA PRO 实践04 - 调试器]]></title>
        <id>NoX7C_Vcf_ipSxmqS0wrNA</id>
        <link href="https://mp.weixin.qq.com/s/NoX7C_Vcf_ipSxmqS0wrNA"/>
        <updated>2024-10-29T16:19:31.000Z</updated>
        <author>
            <name>二手的程序员</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[C4安全团队邀您共筑网络安全防线，提供专业网安服务]]></title>
        <id>sjRqGfVAODvRgNcNBr04CA</id>
        <link href="https://mp.weixin.qq.com/s/sjRqGfVAODvRgNcNBr04CA"/>
        <updated>2024-10-29T16:06:16.000Z</updated>
        <author>
            <name>Code4th安全团队</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[关于普渡大学李宁辉教授《净化安全圈学术环境》的一些看法]]></title>
        <id>oc4HIyB_HsXs77TZIl2Dug</id>
        <link href="https://mp.weixin.qq.com/s/oc4HIyB_HsXs77TZIl2Dug"/>
        <updated>2024-10-29T13:17:41.000Z</updated>
        <author>
            <name>BurpSuite实战教程</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[为什么多数程序员都不做个人独立开发？]]></title>
        <id>ArgD0x5dFg2lxd21jVCjag</id>
        <link href="https://mp.weixin.qq.com/s/ArgD0x5dFg2lxd21jVCjag"/>
        <updated>2024-10-29T03:05:31.000Z</updated>
        <author>
            <name>沉默王二</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[CVE 庆祝成立 25 周年：守护网络空间 25 周年]]></title>
        <id>YQfDt_5E1jPNybHJbmaPhw</id>
        <link href="https://mp.weixin.qq.com/s/YQfDt_5E1jPNybHJbmaPhw"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[中文黑客工具包和活动历史曝光]]></title>
        <id>MsFBHq167CUC6JtuGSaZIw</id>
        <link href="https://mp.weixin.qq.com/s/MsFBHq167CUC6JtuGSaZIw"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[飞利浦智能灯泡对家庭 Wi-Fi 安全构成威胁]]></title>
        <id>z9zrEH14evQ5Rz8RExgflA</id>
        <link href="https://mp.weixin.qq.com/s/z9zrEH14evQ5Rz8RExgflA"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[Realtek SD 读卡器驱动程序中的漏洞影响戴尔、联想和其他笔记本电脑]]></title>
        <id>8YWaJNekzcYBjdZ-jUpwaQ</id>
        <link href="https://mp.weixin.qq.com/s/8YWaJNekzcYBjdZ-jUpwaQ"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[再推荐一下我的小号保命]]></title>
        <id>VwSm3w_J1-arRK0Hn5gZrw</id>
        <link href="https://mp.weixin.qq.com/s/VwSm3w_J1-arRK0Hn5gZrw"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[【poc】Xlight FTP 服务器存在 RCE漏洞CVE-2024-46483 (CVSS 9.8)]]></title>
        <id>ag7ytdN9QH8auc4623ULFA</id>
        <link href="https://mp.weixin.qq.com/s/ag7ytdN9QH8auc4623ULFA"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[突破ChatGPT-4o 安全防护：使用十六进制编码生成 CVE 漏洞利用代码]]></title>
        <id>ioSJOGJfg11W0qVPNgXYCQ</id>
        <link href="https://mp.weixin.qq.com/s/ioSJOGJfg11W0qVPNgXYCQ"/>
        <updated>2024-10-29T02:53:40.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[这些网络安全证书你们可能忽略了，它竟然是。。。]]></title>
        <id>7XnQj0OkVp4W4_3OdNkREA</id>
        <link href="https://mp.weixin.qq.com/s/7XnQj0OkVp4W4_3OdNkREA"/>
        <updated>2024-10-29T02:17:13.000Z</updated>
        <author>
            <name>泷羽Sec</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[双十一团队抽奖活动开奖啦！速来围观]]></title>
        <id>XS2A0JW7BYpcxpMjc4mGsQ</id>
        <link href="https://mp.weixin.qq.com/s/XS2A0JW7BYpcxpMjc4mGsQ"/>
        <updated>2024-10-28T15:52:28.000Z</updated>
        <author>
            <name>Code4th安全团队</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[IDA PRO 实践03 - 函数栈逆向分析]]></title>
        <id>5FyxQuiaC-4_Fs11yLRb3A</id>
        <link href="https://mp.weixin.qq.com/s/5FyxQuiaC-4_Fs11yLRb3A"/>
        <updated>2024-10-28T15:50:06.000Z</updated>
        <author>
            <name>二手的程序员</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[写给网络安全/信息安全/网络空间安全同学掏心窝的话]]></title>
        <id>EG1g_Ns95o9iWvy-8N1CRQ</id>
        <link href="https://mp.weixin.qq.com/s/EG1g_Ns95o9iWvy-8N1CRQ"/>
        <updated>2024-10-28T15:01:04.000Z</updated>
        <author>
            <name>BurpSuite实战教程</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[“我，在字节月薪6万，离职后突然惊醒：人越努力，只会越平庸”]]></title>
        <id>ltNbl4jCnzUkCRD33Kr0fQ</id>
        <link href="https://mp.weixin.qq.com/s/ltNbl4jCnzUkCRD33Kr0fQ"/>
        <updated>2024-10-28T11:16:32.000Z</updated>
        <author>
            <name>沉默王二</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[应届生第一次拒绝24k的工作。]]></title>
        <id>yR2ob5900ALyaF1KET01yw</id>
        <link href="https://mp.weixin.qq.com/s/yR2ob5900ALyaF1KET01yw"/>
        <updated>2024-10-28T11:16:32.000Z</updated>
        <author>
            <name>沉默王二</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[HarmonyOS Next模拟器Root（无视模拟器镜像完整性验证）]]></title>
        <id>GKXHXMdw-i9Jx4P3T-PxEQ</id>
        <link href="https://mp.weixin.qq.com/s/GKXHXMdw-i9Jx4P3T-PxEQ"/>
        <updated>2024-10-28T08:11:12.000Z</updated>
        <author>
            <name>移动安全星球</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[XSS高级用法，SEO优化，挂ma，MS14_064]]></title>
        <id>68Rk5g433Kcvjj607AsoWw</id>
        <link href="https://mp.weixin.qq.com/s/68Rk5g433Kcvjj607AsoWw"/>
        <updated>2024-10-28T04:33:59.000Z</updated>
        <author>
            <name>泷羽Sec</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[小米设备存在的几个命令执行漏洞 -- 已提交修复]]></title>
        <id>BJ3b9AyB3KtU24ybCkp_dw</id>
        <link href="https://mp.weixin.qq.com/s/BJ3b9AyB3KtU24ybCkp_dw"/>
        <updated>2024-10-28T04:27:28.000Z</updated>
        <author>
            <name>合规渗透</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[每周网络安全新闻简报]]></title>
        <id>MaCTuOdaaUA16kOuDCJb7g</id>
        <link href="https://mp.weixin.qq.com/s/MaCTuOdaaUA16kOuDCJb7g"/>
        <updated>2024-10-28T03:10:00.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[美国又悬赏 1000 万美元抓黑客（祖传 1000 万啊）]]></title>
        <id>r5rR9fXn63rubuw9auJKZg</id>
        <link href="https://mp.weixin.qq.com/s/r5rR9fXn63rubuw9auJKZg"/>
        <updated>2024-10-28T03:10:00.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[黑客利用 Verizon 漏洞渗透特朗普手机]]></title>
        <id>nAMXUJSw-STPSeedBCaSIw</id>
        <link href="https://mp.weixin.qq.com/s/nAMXUJSw-STPSeedBCaSIw"/>
        <updated>2024-10-28T03:10:00.000Z</updated>
        <author>
            <name>独眼情报</name>
        </author>
    </entry>
    <entry>
        <title type="html"><![CDATA[68k很稳！师傅们，这个新方向火了！]]></title>
        <id>Bd0UKGYIXeI8LsLrQgRoug</id>
        <link href="https://mp.weixin.qq.com/s/Bd0UKGYIXeI8LsLrQgRoug"/>
        <updated>2024-10-27T20:42:50.000Z</updated>
        <author>
            <name>潇湘信安</name>
        </author>
    </entry>
</feed>
